FROM ubuntu:22.04
RUN apt update
RUN apt install -y vim git make mpich libhdf5-mpich-dev
ENV HDF_HOME="/usr/lib/x86_64-linux-gnu/hdf5/mpich"

# Run test with > mpirun -np 2 ./harm3d "2" "1" "1" "6" "6" "6"
